/* eslint no-console: 0 */
import '../imports/client/ui/home.html'
// import '../imports/client/ui/home.js'
import '../imports/client/ui/search.html'
import '../imports/client/ui/search.js'
import '../imports/client/ui/tx.html'
import '../imports/client/ui/tx.js'
import '../imports/client/ui/tokens.html'
import '../imports/client/ui/tokens.js'
import '../imports/client/ui/block.html'
import '../imports/client/ui/block.js'
import '../imports/client/ui/address.html'
import '../imports/client/ui/address.js'
import '../imports/client/ui/progress.html'
import '../imports/client/routes.js'
import './test-methods.js'
