root: true
# enable ES6
parserOptions:
  ecmaVersion: 2017
  sourceType: "module"
  ecmaFeatures:
    jsx: true # enable React's JSX

extends:
  - airbnb-base

# registerenvironments
env:
  meteor: true
  browser: true
  node: true
  es6: true

rules:
  # overwrite some rules (avoid semicolons) 
  semi: [2, 'never']
  no-unexpected-multiline: 2
  no-throw-literal: 0
  no-console: 0
  func-names: 0
  no-plusplus: 0
  no-param-reassign:
    - 2
    - props: false
  max-len: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  import/no-absolute-path: 0
  import/no-cycle: 0
  # import/no-unresolved: 0
  import/extensions:
    - off
    - never
  # import/no-extraneous-dependencies: 0

globals:
  # collections
  # Foo: false
  # Bar: false

  # packages
  FlowRouter: false # kadira:flow-router
  moment: false # momentjs:moment
  BlazeLayout: false
  LocalStore: false # frozeman:storage
  ApexCharts: false # loaded via public/apexcharts.min.js

overrides:
  - files:
      - imports/startup/server/*.js
    rules:
      no-use-before-define: 0
      no-restricted-syntax: 0
      no-await-in-loop: 0
      no-continue: 0
      consistent-return: 0
      no-return-await: 0
  
settings:
  import/core-modules: [ meteor ]
  import/resolver: meteor
